### ISSUE TITLE
Should check_ev20_idg.py fail for other nodes replying?

### ISSUE THREAD

**Issue by atanisoft** [bobjacobsen/OlcbChecker#6]
In the case of a CS that has one (or more) virtual train nodes they will reply to the `MTI.Identify_Events_Global` message appearing on the bus automatically. Currently this triggers a FAIL response from check_ev20_idg.py since the message(s) coming in are considered unexpected.

Can/should this be accepted/relaxed as long as the target node does respond to the event request?

**Comment by bobjacobsen** [comment]
Good point!  Will fix, might be a day or two.

**Comment by bobjacobsen** [comment]
PR #8 turns these into just info messages.  Or would just silently absorbing them be better?

**Comment by atanisoft** [comment]
I think info is fine.
