### ISSUE TITLE
quit action doesn't appear to close the serial link cleanly

### ISSUE THREAD

**Issue by atanisoft** [bobjacobsen/OlcbChecker#7]
In my tests with a USB interface, I'm not seeing a disconnect event raised when the checker exits. It seems that the port is a left in an open state upon program exit rather than being terminated as JMRI and other tools would do.

This may need to be implemented on the python-openlcb side as well as here.

**Comment by bobjacobsen** [comment]
Can I get a bit more info?

Sounds like you're running it via one of the `control_*.py` scripts.  Is that right?  Or are you running a `check_*.py` script directly?

What are the symptoms of the port being left open?  

And what kind of computer is this, i.e. Mac, Linux, Windows?

Thanks, and sorry for the trouble.

**Comment by atanisoft** [comment]
Sorry, should have included that info. This is on Linux and the behavior is different to how JMRI operates.

JMRI example showing the known disconnect:
```
00:00:30.449: heap:101.57kB (max block:30.99kB), PSRAM:1880.43kB (max block:1855.99kB), mainBufferPool:2.38kB, tasks:18
GCHubPort: Shutting down gridconnect port -1. (0x3fce69f4)
00:00:45.452: heap:102.85kB (max block:30.99kB), PSRAM:1884.66kB (max block:1855.99kB), mainBufferPool:2.38kB, tasks:18
```
JMRI is connected just before the first timestamp and shows the disconnect within a few seconds of when it actually occurs.

When running `python control_master.py -d /dev/ttyACM0 -t 02.02.05.01.49.b9` sometimes the disconnect occurs, other times it doesn't. When it doesn't disconnect the `control_master.py` script appears stuck with no traffic being interchanged (which looks to be due to USB not cleanly disconnecting). When this no traffic issue shows up, if I close the python code and start JMRI it is working as expected.

I've also seen a case where if the USB device reenumerates it crashes the serial link but not the program (it should likely close and try to reopen when there is an error).

**Comment by bobjacobsen** [comment]
Working on this.  It's going to require some additions to the openlcb Python library API, so I'm working on getting that included as a sub-project first.

**Comment by bobjacobsen** [comment]
I've just updated the control*.py files to do a close on exit.  Could you please check this to see if it resolves this? You'll need the head of this repository, and the head (or at least the v0.1.2 tag) of the python-openlcb repository.  

(I'm still working on how to better distribute those together)

If this works, I can make a similar change to the check*.py files for when those are run stand-alone.

**Comment by atanisoft** [comment]
I'll give it a test in the morning and let you know

**Comment by atanisoft** [comment]
Looks like the latest works much more consistently. I'm encountering a different bug but I don't think it is related to the python code so I'll be investigating that next but this issue can be closed at this point I think.

**Comment by bobjacobsen** [comment]
Thank you!  I'll go ahead and update the check*py files, hopefully later today.
